name: Build and publish documentation

on:
  push:

env:
  # branch that contains the lastest version of the documentation
  # when building this branch we create the version list and switcher
  # so that they can be published on the website
  LATEST_BRANCH: refs/heads/main

jobs:

  build:
    name: Build doc
    runs-on: ubuntu-latest

    steps:

       - name: Checking out documentation sources
         uses: actions/checkout@v4
         with:
           path: doc
           lfs: true

       - name: Checking out framework sources
         uses: actions/checkout@v4
         with:
           path: framework
           repository: synaptics-astra/synap-framework
           ref: v1.0.0

       - name: Build documentation
         uses: ./doc/.github/actions/build-doc

       - name: Upload GitHub Pages artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: doc/_build/site


  publish:
    name: Publish doc to GitHub Pages
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
